### ISSUE TITLE
Wrong reference in README

### ISSUE THREAD

**Issue by Eridani117** [rentruewang/learning-machine#11]
It's seems [README.md#L59](https://github.com/rentruewang/learning-machine/blob/main/README.md?plain=1#L59)
is wrong .
``
  59- [Auto Regression](./book/tasks/regression/regression.ipynb)
``
should be changed to 
`` 
  59- [Auto Regression](./book/tasks/regression/auto/auto.ipynb)
``

**Comment by rentruewang** [comment]
Hi, thanks for the report! It seems like I'd forgotten to update my `README.md`.
